### PR TITLE
Limiting precision on decimal input to max of 2 points

### PR DESCRIPTION
**Pull request by chewbakartik**
Seems like this could be a useful change to change the precision of the decimal point.

### CODE REVIEW

**Comment by thatmarvin** [comment]
Unfortunately we cannot assume 2 decimals places; there are currencies that use 3 or 4 decimal places (see https://en.wikipedia.org/wiki/ISO_4217), and also in cases like displaying currency exchange rates (see www.xe.com).

What was the problem that you were trying to solve?

**Comment by chewbakartik** [comment]
While that makes sense, perhaps it should be a configurable value set by each developer using the directive.  I was working on a form where the value validation requirement was to limit to 2 decimal points.

**Comment by thatmarvin** [comment]
If you look at the [demo](https://fiestah.github.io/angular-money-directive/), in the second section where you can specify the precision, it does round off to the specific precision if you enter something longer. Is that behavior insufficient?

I just noticed that the rounding doesn't happen if there are other errors, like if you exceed the max for example. Not sure what the desired behavior is here

**Comment by chewbakartik** [comment]
The change I had suggested was just trying to prohibit the user from entering values beyond the precision value.  I can see in your demo that as you leave the input field, the value gets set to whatever the precision is.  Much like how you can't put in more than one decimal point, I was trying to not allow the user to enter more than 2 (or in a variable configuration x) values beyond the decimal.

**Pull request closed without merging**
