### PR TITLE
Fixed NaN issue when parsing numeric input

### PR DESCRIPTION
**Pull request by b3by**
The issue with NaN value passed after passing seems to be fixed. Tests are passing too.

### CODE REVIEW

**Comment by thatmarvin** [comment]
Thanks for the PR! Mind adding a test case that fails before your patch, but passes after?

**Comment by b3by** [comment]
Sure thing man, unfortunately I'm at work, I will add it as soon as I go
back home!
Cheers!
On Jun 11, 2015 5:08 AM, "Marvin Tam" <notifications@github.com> wrote:
>
> Thanks for the PR! Mind adding a test case that fails before your patch,
but passes after?

**Comment by b3by** [comment]
Still there, not really sure what do you have in mind for this test? How can I test the behavior before the patch and after the patch?

**Comment by thatmarvin** [comment]
Not sure how familiar are you with unit testing — but usually before I go fix a bug, I'd write a test case that confirms the bug is happening, which means the test case will fail as expected. Once I've actually patched it, the test case will pass and I'm done.

So in this case, I'd write the test case on `master`, which will fail as expected; once you switch to this branch with your fix, the same test case should now pass.

**Comment by spencerwi** [comment]
So I pulled down `master` and tried to write a test case that fails, to no avail.

Then it occurred to me that we're seeing the errant behavior in our angular 1.4 app, so I upped the bower.json dependency to 1.4 -- and several tests broke, including mine in the way described in this issue.

So I'd say the bigger issue is that the directive has some broken areas for 1.4.x - if I had to guess at the root cause based on the tests that are failing, I'd say it's some interesting new scoping issue.

**Comment by b3by** [comment]
Did you also try to run the tests with the patch? I was not able to write failing test cases for this scenario, but the fix should still be valid. Not sure how it's going to behave with 1.4 though.

**Comment by spencerwi** [comment]
After applying the patch, there're still some other, unrelated tests failing showing similar issues with default values for `min` and `max`

**Comment by spencerwi** [comment]
After poking around the tests and code some more, it looks like the biggest culprits for the breakage are the changes that occurred between Angular 1.2 and 1.3 such that view values are not automatically committed, and the fact that this directive does validation the "old way" using `ngModelCtrl.$parsers` and `ngModelCtrl.$formatters` rather than `ngModelCtrl.$validators` (see [here](http://blog.thoughtram.io/angularjs/2015/01/11/exploring-angular-1.3-validators-pipeline.html) for more details)

**Comment by thatmarvin** [comment]
I've overhauled the part that handles precision in another commit, so no longer need this.

**Pull request closed without merging**
